from django.http.request import HttpRequest
from django.contrib.auth.models import User

from six import text_type

def authenticate(username: text_type, password: text_type) -> User: ...
def login(request: HttpRequest, user: User) -> None: ...
def logout(requet: HttpRequest) -> None: ...
