from django.db.models import Manager
from main.models import State, District, SubDistrict, School, Volunteer, Registration

def dummyStateManager() -> Manager[State]: ...
def dummyDistrictManager() -> Manager[District]: ...
def dummySubDistrictManager() -> Manager[SubDistrict]: ...
def dummySchoolManager() -> Manager[School]: ...
def dummyVolunteerManager() -> Manager[Volunteer]: ...
def dummyRegistrationManager() -> Manager[Registration]: ...
